### ISSUE TITLE
Source code is not being extracted

### ISSUE THREAD

**Issue by lucia-developer** [KhanhNguyen9872/deobf_pyobfuscate.com#12]
root@XXX:~# python3 pyd_pyobf_deobf.py
>> input file path: obf.py
>> source code: 
Traceback (most recent call last):
  File "<string>", line 12, in <module>
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/pyd_pyobf_deobf.py", line 45, in <module>
    exec(file)
  File "<string>", line 6, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 23, in <module>
  File "<string>", line 1
    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    ^
SyntaxError: invalid syntax

**Comment by KhanhNguyen9872** [comment]
> root@XXX:~# python3 pyd_pyobf_deobf.py
> 
> > > input file path: obf.py
> > > source code:
> > > Traceback (most recent call last):
> > > File "", line 12, in 
> > > TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/root/pyd_pyobf_deobf.py", line 45, in exec(file) File "", line 6, in File "", line 1, in File "", line 1, in File "", line 1, in File "", line 23, in File "", line 1 ^ SyntaxError: invalid syntax

can you give me your obf file?

**Comment by KhanhNguyen9872** [comment]
> root@XXX:~# python3 pyd_pyobf_deobf.py
> 
> > > input file path: obf.py
> > > source code:
> > > Traceback (most recent call last):
> > > File "", line 12, in 
> > > TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/root/pyd_pyobf_deobf.py", line 45, in exec(file) File "", line 6, in File "", line 1, in File "", line 1, in File "", line 1, in File "", line 23, in File "", line 1 ^ SyntaxError: invalid syntax

this repo is alway up to date with pyobfuscate, if you can't deobf it, try old version in commit [here](https://github.com/KhanhNguyen9872/deobf_pyobfuscate.com/commits/main/)

**Comment by KhanhNguyen9872** [comment]
closed due to no response
